TITLE = "Most Dangerous Writing App"
WINDOW_RESOLUTION = "640x550"
PADX = 20
PADY = 10
FONT = ("Arial", 12, "bold")
TEXTBOX_WIDTH = 65

# timer durations in seconds
SESSION_DURATION = 15
CLEARING_DURATION = 5

# colour palette
FONT_COLOUR = "#EEEEEE"
LABEL_COLOUR = "#00ADB5"
WINDOW_COLOUR = "#393E46"
TEXTBOX_COLOUR = "#222831"
